apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata: 
 name: mypod  
spec:
 containers: 
 - name: app1 
   image: supergiantkir/animals:bear
   volumeMounts:
    - mountPath: /storage
      name: app-storage
 - name: app2
   image: yanivomc/spring-music:latest
   volumeMounts:
    - mountPath: /storage
      name: app-storage  
 volumes:
  - name: app-storage
    hostPath:
        # directory location on host
    path: /tmp/files
